package mnn

/*
#include <ErrorCode_c.h>
#include <stdlib.h>
*/
import "C"

// ErrorCode 定义MNN的错误码
type ErrorCode int

const (
	NO_ERROR           ErrorCode = C.MNN_NO_ERROR
	OUT_OF_MEMORY      ErrorCode = C.MNN_OUT_OF_MEMORY
	NOT_SUPPORT        ErrorCode = C.MNN_NOT_SUPPORT
	COMPUTE_SIZE_ERROR ErrorCode = C.MNN_COMPUTE_SIZE_ERROR
	NO_EXECUTION       ErrorCode = C.MNN_NO_EXECUTION
	INVALID_VALUE      ErrorCode = C.MNN_INVALID_VALUE

	// User error
	INPUT_DATA_ERROR ErrorCode = C.MNN_INPUT_DATA_ERROR
	CALL_BACK_STOP   ErrorCode = C.MNN_CALL_BACK_STOP

	// Op Resize Error
	TENSOR_NOT_SUPPORT ErrorCode = C.MNN_TENSOR_NOT_SUPPORT
	TENSOR_NEED_DIVIDE ErrorCode = C.MNN_TENSOR_NEED_DIVIDE

	// File error
	FILE_CREATE_FAILED ErrorCode = C.MNN_FILE_CREATE_FAILED
	FILE_REMOVE_FAILED ErrorCode = C.MNN_FILE_REMOVE_FAILED
	FILE_OPEN_FAILED   ErrorCode = C.MNN_FILE_OPEN_FAILED
	FILE_CLOSE_FAILED  ErrorCode = C.MNN_FILE_CLOSE_FAILED
	FILE_RESIZE_FAILED ErrorCode = C.MNN_FILE_RESIZE_FAILED
	FILE_SEEK_FAILED   ErrorCode = C.MNN_FILE_SEEK_FAILED
	FILE_NOT_EXIST     ErrorCode = C.MNN_FILE_NOT_EXIST
	FILE_UNMAP_FAILED  ErrorCode = C.MNN_FILE_UNMAP_FAILED
)
